version: '3.8'

services:
  db:
    image: mongo:4.4.28
    env_file:
      - .env.docker
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  server:
    build: ./server
    env_file:
      - .env.docker
    container_name: fastapi_server
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build: ./client
    env_file:
      - .env.docker
    container_name: nextjs_client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongodata:
